### ISSUE TITLE
Inventory unexpectedly marked as Low Stock 

### ISSUE THREAD

**Issue by gigincg** [ohcnetwork/care#725] opened 2022-04-24 06:39 UTC
Creating a PPE Inventory, without having a Minimum Quantity marks it as Low Stock. This shouldn't be the case

**Comment by iamsdas** [comment] 2022-05-10 14:53
@gigincg is this issue still valid? I am unable to reproduce this issue locally.
(I tried creating a new inventory without specifying the `min_quantity` using the swagger UI. The resulting inventory summary does not have low stock)
![Screenshot_20220510_202231](https://user-images.githubusercontent.com/26461855/167658004-fbd02fe9-b367-43f2-a624-b80db8aca4e7.png)

**Comment by gigincg** [comment] 2022-05-20 04:04
@nihal467 had replicated it again in #2437

**Comment by suhani221** [comment] 2024-03-19 20:16
has this issue been resolved?

**Comment by slimkevo** [comment] 2024-08-02 16:37
Can I be assigned this issue?

**Comment by Harsh-D-2004** [comment] 2024-12-05 10:17
@gigincg 
Is this resolved or can i be assigned this?

**Closed** 2024-12-31 10:26 UTC
Labels: good first issue, question, hacktoberfest
